import type { Metadata } from "next";

import "./css/base.css";
import "./css/font.css";
import "./css/style.css";
import "./css/style.scss";

import "./css/fontello/css/animation.css";
import "./css/fontello/css/fontello.css";

import Link from 'next/link';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>

        <header>
          <Link href="/">
            <div className="img_logo"></div>
          </Link>

          <nav>
            <Link href="/project">Project</Link>
          </nav>
        </header>

        {children}

      </body>
    </html>
  );
}
